CREATE DATABASE cad_etec_cps;

USE cad_etec_cps;

CREATE TABLE CADASTRO
	(ID 		BIGINT 			NOT NULL 	PRIMARY KEY auto_increment,
	 NOME 		VARCHAR(50) 	NOT NULL,
     CODIGO 	INT 			NOT NULL,
     CEP 		VARCHAR(12) 	NOT NULL,
     ENDERECO 	VARCHAR(50) 	NOT NULL,
     BAIRRO 	VARCHAR(30) 	NOT NULL,
     CIDADE 	VARCHAR(30)		NOT NULL,
     LATITUDE 	DOUBLE 			NOT NULL,
     LONGITUDE 	DOUBLE 			NOT NULL);
     
DROP DATABASE cad_etec_cps